### ISSUE TITLE
OpenCascade Exception when Creating Grids

### ISSUE THREAD

**Issue by kikootwo** [xBimTeam/XbimWindowsUI#88]
Hello,

If you have instantiated an IFCGRID type, and have not defined these lines:

`#43= IFCDIMENSIONALEXPONENTS(1,0,0,0,0,0,0);`
`#44= IFCMEASUREWITHUNIT(IFCRATIOMEASURE(0.3048),#42);`
`#45= IFCCONVERSIONBASEDUNIT(#43,.LENGTHUNIT.,'FOOT',#44);`

XbimXplorer will throw this exception 
![image](https://user-images.githubusercontent.com/14036771/42663541-eff83c8a-8603-11e8-8e53-da903cbe9a62.png)

To recreate this bug, remove your reference to IFCCONVERSIONBASEDUNIT from unit assignment in any file with an IFCGRID. Please let me know if you need any additional information.

**Comment by martin-loucka** [comment]
yes... the same issue

   at BRepOffsetAPI_MakePipe.{ctor}(BRepOffsetAPI_MakePipe* , TopoDS_Wire* , TopoDS_Shape* )
   at Xbim.Geometry.XbimGeometryCreator.CreateGrid(IIfcGrid grid)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries(XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, IGeometryStoreInitialiser geometryStore, XbimGeometryType geomStorageType) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 1136
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 676
   at UnitTestsIMModell.xBim.Readers.GeoReader.ReadGeo(String ifcFileName) in C:\01_Work\06_Senn\01_Code\99_Tests\_UnitTests\xBim\Readers.cs:line 89

**Comment by martin-loucka** [comment]
at BRepOffsetAPI_MakePipe.{ctor}(BRepOffsetAPI_MakePipe* , TopoDS_Wire* , TopoDS_Shape* )
   at Xbim.Geometry.XbimGeometryCreator.CreateGrid(IIfcGrid grid)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries(XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, IGeometryStoreInitialiser geometryStore, XbimGeometryType geomStorageType) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 1136
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 676
   at UnitTests.xBim.Readers.GeoReader.ReadGeo(String ifcFileName) in C:\01_Work\06_Senn\01_Code\99_Tests\_UnitTests\xBim\Readers.cs:line 89
